"""
Cross-platform hosts file manager with a managed marker block.

Adapted from ZapretGUI hosts/hosts.py: preserves foreign content, rewrites
only the managed block, and locates the hosts path per OS.
"""
from __future__ import annotations

import logging
import os
import subprocess
import sys
import tempfile
from pathlib import Path
from typing import Dict, List, Optional, Set, Tuple

log = logging.getLogger("swift-hosts")

MANAGED_BEGIN = "# >>> swiftproxy:hosts managed begin >>>"
MANAGED_END = "# <<< swiftproxy:hosts managed end <<<"
MANAGED_NOTICE = "# Generated by SwiftProxy. Do not edit this block manually."


def _get_hosts_path() -> Path:
    if sys.platform == "win32":
        sys_root = os.environ.get("SystemRoot") or os.environ.get("WINDIR")
        if sys_root:
            return Path(sys_root, "System32", "drivers", "etc", "hosts")
        return Path(r"C:\Windows\System32\drivers\etc\hosts")
    return Path("/etc/hosts")


HOSTS_PATH = _get_hosts_path()


def _parse_hosts_mapping_line(line: str) -> Optional[Tuple[str, List[str], str]]:
    mapping_part, sep, comment_part = str(line or "").partition("#")
    mapping_stripped = mapping_part.strip()
    if not mapping_stripped:
        return None
    parts = mapping_stripped.split()
    if len(parts) < 2:
        return None
    return parts[0], parts[1:], comment_part.strip() if sep else ""


def _format_hosts_mapping_line(ip: str, domains: List[str], comment: str) -> str:
    line = f"{ip} {' '.join(domains)}"
    if comment:
        line += f" # {comment}"
    return line + "\n"


def _remove_managed_hosts_block(lines: List[str]) -> Tuple[List[str], int]:
    new_lines: List[str] = []
    removed_entries = 0
    inside_block = False
    for line in lines:
        stripped = line.strip()
        if stripped == MANAGED_BEGIN:
            inside_block = True
            continue
        if inside_block:
            if stripped and not stripped.startswith("#"):
                removed_entries += 1
            if stripped == MANAGED_END:
                inside_block = False
            continue
        new_lines.append(line)
    return new_lines, removed_entries


def _remove_top_domain_entries(
    lines: List[str], domain_keys: Set[str]
) -> Tuple[List[str], Set[str], Optional[int]]:
    """Remove the first occurrence of each target domain; remember the insert point."""
    if not domain_keys:
        return lines, set(), None

    new_lines: List[str] = []
    removed_keys: Set[str] = set()
    insert_at: Optional[int] = None

    for line in lines:
        parsed = _parse_hosts_mapping_line(line)
        if parsed is None:
            new_lines.append(line)
            continue
        ip, domains, comment = parsed
        matched_keys = {
            d.casefold()
            for d in domains
            if d.casefold() in domain_keys and d.casefold() not in removed_keys
        }
        if not matched_keys:
            new_lines.append(line)
            continue
        if insert_at is None:
            insert_at = len(new_lines)
        removed_keys.update(matched_keys)
        remaining = [d for d in domains if d.casefold() not in matched_keys]
        if remaining:
            new_lines.append(_format_hosts_mapping_line(ip, remaining, comment))
    return new_lines, removed_keys, insert_at


def read_hosts_file() -> List[str]:
    try:
        return HOSTS_PATH.read_text(encoding="utf-8", errors="replace").splitlines(True)
    except OSError:
        return []


def write_hosts_file(lines: List[str]) -> None:
    """Atomically write hosts content (temp file + rename); needs admin/root on most OSes."""
    HOSTS_PATH.parent.mkdir(parents=True, exist_ok=True)
    fd, tmp_path = tempfile.mkstemp(
        prefix=".hosts.", suffix=".tmp", dir=str(HOSTS_PATH.parent)
    )
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as f:
            f.writelines(lines)
        os.replace(tmp_path, HOSTS_PATH)
    except Exception:
        try:
            os.unlink(tmp_path)
        except OSError:
            pass
        raise


def _build_managed_lines(entries: Dict[str, str], notice: str) -> List[str]:
    result = [MANAGED_BEGIN + "\n", "# " + notice + "\n"]
    for domain in sorted(entries):
        ip = entries[domain]
        result.append(_format_hosts_mapping_line(ip, [domain], ""))
    result.append(MANAGED_END + "\n")
    return result


def apply_host_entries(entries: Dict[str, str]) -> Tuple[bool, int]:
    """Write the given domain->IP map inside the managed block. Returns (ok, count)."""
    lines = read_hosts_file()
    domain_keys = {d.casefold() for d in entries}

    lines, _removed, _insert = _remove_managed_hosts_block(lines)
    lines, removed_keys, insert_at = _remove_top_domain_entries(lines, domain_keys)

    managed = _build_managed_lines({k: v for k, v in entries.items()}, MANAGED_NOTICE)
    if insert_at is not None:
        lines[insert_at:insert_at] = managed
    else:
        lines.extend(managed)

    try:
        write_hosts_file(lines)
        return True, len(entries)
    except OSError as exc:
        log.warning("Failed to write hosts: %s", repr(exc))
        return False, 0


def clear_host_entries() -> Tuple[bool, int]:
    """Remove all SwiftProxy-managed entries. Returns (ok, removed count)."""
    lines = read_hosts_file()
    lines, removed = _remove_managed_hosts_block(lines)
    try:
        write_hosts_file(lines)
        return True, removed
    except OSError as exc:
        log.warning("Failed to clear hosts: %s", repr(exc))
        return False, removed


def read_active_domains_map() -> Dict[str, str]:
    """Read current managed block entries as domain->ip."""
    result: Dict[str, str] = {}
    inside = False
    for line in read_hosts_file():
        stripped = line.strip()
        if stripped == MANAGED_BEGIN:
            inside = True
            continue
        if stripped == MANAGED_END:
            inside = False
            continue
        if not inside or not stripped or stripped.startswith("#"):
            continue
        parsed = _parse_hosts_mapping_line(line)
        if parsed:
            ip, domains, _comment = parsed
            for d in domains:
                result[d] = ip
    return result


def open_hosts_file() -> None:
    """Open the hosts file in the OS default editor."""
    if sys.platform == "darwin":
        subprocess.Popen(["open", str(HOSTS_PATH)])
    elif sys.platform == "win32":
        subprocess.Popen(["notepad", str(HOSTS_PATH)])
    else:
        subprocess.Popen(["xdg-open", str(HOSTS_PATH)])


def get_hosts_path_str() -> str:
    return str(HOSTS_PATH)