"""
Пакет профилей winws: serializer (текст <-> модель) + instance (хранилище).

Заменяет бывший модуль ``winws/profiles.py``: весь его публичный API сохранён
(``list_user_profiles``, ``resolve_profile``, ``engine_mode_for`` ...) и
дополнен profile-подсистемой для редактора профилей.
"""
from .serializer import (
    GROUP_CODES,
    GROUP_CONFIG,
    GROUP_FILTER,
    GROUP_HOSTLIST,
    GROUP_LUA,
    GROUP_PARAMS,
    VALUE_TYPE_AT,
    VALUE_TYPE_CODES,
    VALUE_TYPE_FLAG,
    VALUE_TYPE_INT,
    VALUE_TYPE_OPTIONS,
    VALUE_TYPE_STR,
    VALUE_TYPE_VECTOR,
    Line,
    Param,
    ProfileModel,
    apply_strategy,
    classify_group,
    describe,
    detect_value_type,
    parse_profile_text,
    round_trip,
    serialize_profile,
    validate_profile,
)
from .instance import (
    _GROUPS,
    _PROFILE_NAME_RE,
    _safe_user_path,
    delete_user_profile,
    engine_mode_for,
    ensure_recommended,
    get_active_profile,
    get_user_profile_text,
    is_recommended,
    list_user_profiles,
    profile_delete,
    profile_dir,
    profile_list,
    profile_read,
    profile_reset,
    profile_write,
    resolve_profile,
    save_user_profile,
    set_active_profile,
)

__all__ = [
    "apply_strategy",
    "classify_group",
    "describe",
    "detect_value_type",
    "delete_user_profile",
    "engine_mode_for",
    "ensure_recommended",
    "get_active_profile",
    "get_user_profile_text",
    "is_recommended",
    "list_user_profiles",
    "parse_profile_text",
    "profile_delete",
    "profile_dir",
    "profile_list",
    "profile_read",
    "profile_reset",
    "profile_write",
    "resolve_profile",
    "round_trip",
    "save_user_profile",
    "serialize_profile",
    "set_active_profile",
    "validate_profile",
    "Line",
    "Param",
    "ProfileModel",
]